export type AmbassadorRecord = {
  slug: string;
  name: string;
  institution: string;
  email: string;
  bio: string;
  photoSrc?: string;
};

export const ambassadorDirectory: AmbassadorRecord[] = [
  {
    slug: "aayat-irfan-qureshi",
    name: "Aayat Irfan Qureshi",
    institution: "Curtin Mauritius",
    email: "aayatearth@gmail.com",
    bio: "I am a young emerging writer, poet and changemaker passionate about sustainability, peace and social issues, climate change, travel and tourism. I am currently pursuing a Bachelor's degree at Curtin Mauritius with a dual specialisation in Marketing Communications and Corporate Screen Communications. Given my array of passions, I have nearly 5 years of experience within the print media, creative non-fiction, storytelling and writing industry. My keen interest in media studies & communications, marketing, and film has driven me to explore my passions beyond just writing.",
  },
  {
    slug: "abdulsamad-oladipo",
    name: "AbdulSamad Oladipo",
    institution: "Lead City University",
    email: "oladiposa3@gmail.com",
    bio: "I am a Dedicated and Enthusiastic Radiography graduate professional with a strong passion for radiation protection and patient care. I started my internship where I gained valuable hands-on clinical experience, and I also attended YMAU V in Ghana, broadening my professional knowledge and network. I am committed to continuous learning and excellence in healthcare. Outside my professional life, I enjoy watching football, which reflects my appreciation for teamwork, discipline, and good relationships.",
  },
  {
    slug: "abut-seleman-tiso",
    name: "Abut Seleman Tiso",
    institution: "United States International University",
    email: "astiso@usiu.ac.ke",
    bio: "My name is Abut Seleman Tiso, a Sudanese fourth-year student at USIU-Africa pursuing a Bachelor of Science in Information Systems and Technology, with a concentration in Cybersecurity and Forensics. In addition to my academic background, I am a full-stack web developer specializing in the Django framework and a data analyst. I have designed and developed a fully functional e-commerce platform with complete user authentication and management features, alongside several other web applications, demonstrating strong expertise in backend development, database design, frontend integration, and data-driven problem-solving.",
  },
  {
    slug: "acka-hobbah-ahou-ruth-esther",
    name: "Acka Hobbah Ahou Ruth Esther",
    institution: "International University of Grand Bassam",
    email: "ackah1@student.iugb.edu.ci",
    bio: "My name is Acka Hobbah Ahou Ruth Esther. A Political Science and International Relations graduate with honors from the International University of Grand-Bassam (IUGB), Côte d’Ivoire. I am a sociable, joyful, and curious person who enjoys connecting with people from diverse backgrounds. My interests include Pan-Africanism, diplomacy, dance and inclusive leadership. As President of the Political Science Assembly in my school, I led initiatives that strengthened student engagement and professional development.Through student leadership and community engagement, I have developed strong communication, team work skills. I aspire to contribute to Africa’s development by empowering young people and promoting collaborative leadership.",
  },
  {
    slug: "adjoba-ruth-marie-akoi",
    name: "Adjoba Ruth Marie Akoi",
    institution: "International University of Grand Bassam ( IUGB)",
    email: "akoia1@student.iugb.edu.ci",
    bio: "I am a curious and ambitious university student from Côte d’Ivoire who is passionate about learning, personal growth, and discovering new cultures. I enjoy exploring social issues, reading, watching films, and expressing my creativity through photography. One of my biggest dreams is to live in Finland and experience its culture and way of life. I believe in resilience, continuous growth, and embracing new opportunities. Every experience teaches me something valuable and motivates me to become the best version of myself.",
  },
  {
    slug: "afanou-yawa-gloria-eslie",
    name: "Afanou Yawa Gloria Eslie",
    institution: "International University of Grand Bassam",
    email: "afanouy1@student.iugb.edu.ci",
    bio: "Gloria Afanou is a Business Administration and Finance student at the International University of Grand-Bassam in Côte d’Ivoire, passionate about African development, economic empowerment, and youth leadership. As a participant in the Yale Model African Union, she has developed a strong interest in diplomacy, international relations, and addressing challenges affecting African economies. Through academic projects, leadership initiatives, and community engagement, Gloria has strengthened her communication, teamwork, research, and problem-solving skills. She believes that young Africans have an essential role to play in shaping the continent’s future. As a YMAU Ambassador, she hopes to inspire others, promote meaningful dialogue, and encourage greater youth participation in African affairs.",
  },
  {
    slug: "ahiadjipe-akossiwa-djifa-eunice",
    name: "Ahiadjipe Akossiwa Djifa Eunice",
    institution: "INTERNATIONAL UNIVERSITY OF GRAND BASSAM",
    email: "ahiadjipea1@student.iugb.edu.ci",
    bio: "My name is Ahiadjipe Akossiwa Djifa Eunice, 21 years old. Student at the International University of Grand Bassam. I am a Jéhovah witness.",
  },
  {
    slug: "akuzwe-viateur",
    name: "Akuzwe Viateur",
    institution: "University of Rwanda",
    email: "akuzwev@gmail.com",
    bio: "I am Viateur AKUZWE, a Rwandan youth leader and development practitioner with a Bachelor of Social Sciences (Hons) in Development Studies from the University of Rwanda. I currently serve as Assistant Sergeant-at-Arms of the East African Youth Parliament and CEO of Bright Coders Rwanda. Previously, I served as Deputy Vice Guild President at the University of Rwanda and represented the College of Arts and Social Sciences as a member of the University of Rwanda Academic Senate. I also participated in Yale Model African Union III (Rwanda) and Yale Model African Union IV (Nairobi), experiences that strengthened my leadership, diplomacy, and public speaking skills. I am passionate about youth empowerment, governance, innovation, and regional cooperation.",
  },
  {
    slug: "akwa-kelly-pride-f",
    name: "Akwa Kelly-Pride F.",
    institution: "United States International University Africa",
    email: "akwakelly2@gmail.com",
    bio: "For Kelly-Pride, leadership is about leaving every person and every community better than she found them. A final year pharmacy student at USIU Africa and Mastercard Foundation Scholar from Cameroon, she is passionate about expanding access to education, advancing health literacy, and empowering young Africans to lead with purpose. She serves as a tutor and mentor at Open Dreams, co organizes Afrocentric Dialogues, a monthly youth forum advancing conversations on Africa's future and the African Union Agenda 2063, and founded A Pill by The Purpose, a platform dedicated to making medication knowledge simple, accessible, and impactful. She believes she is a pill with purpose, bringing healing through knowledge, service, and leadership.",
  },
  {
    slug: "amoah-littiana",
    name: "Amoah Littiana",
    institution: "Kwame Nkrumah university of Science and Technology",
    email: "amoahlittiana@gmail.com",
    bio: "Littiana Amoah is a Ghanaian registered nurse and youth leader passionate about global health, youth empowerment, and sustainable development. She holds a BSc in Nursing from Kwame Nkrumah University of Science and Technology (KNUST) and has served in various public health and community outreach initiatives. As a YMAU VI Ambassador and former YMAU delegate, Littiana is committed to empowering young Africans through leadership, advocacy, and meaningful dialogue. She aspires to contribute to international health and policy by connecting healthcare, diplomacy, and youth-led solutions to advance sustainable development across Africa.",
  },
  {
    slug: "aruei-bior-akauien",
    name: "Aruei Bior AkAuien",
    institution: "University of Juba",
    email: "jacobaruei886@gmail.com",
    bio: "Aruei Bior Akuien, a South Sudanese student leader passionate about leadership, diplomacy, and youth empowerment. I am Experienced educator, leader and communicator with three years of hands-on experience in social start-ups and non-profit organizations. Highly motivated, ambitious, proficient at thriving in fast-paced environments with minimal supervision, and committed to delivering impactful results. Proficient in internal communication and project management, ensuring seamless and effective relationship-building. Always tries to do his best in the current situation —sometimes that means a lot more than expected, and sometimes slightly less when things go wrong; because life does not always come on a silver platter.",
  },
  {
    slug: "ashelly-adeline-mwisha",
    name: "Ashelly Adeline Mwisha",
    institution: "Pestalozzi Academy",
    email: "ashellyadeline403@gmail.com",
    bio: "My name is Ashelly Adeline Mwisha. I am 17 years old. I was born in North Kivu, DR Congo, but in 2015 my family and I fled due to conflict. Today, I live in a refugee camp in Zambia.I am an IGCSE Year 2 student at Pestalozzi Academy on a 100% scholarship. I am passionate about leadership, public speaking, and problem solving. By God’s grace, I have had the privilege of participating in The Ethical Leadership Experience, Yale Young African Scholars, Yale Model African Union V, Girls Who Code, and several Model United Nations conferences online. These experiences have shaped my dreams and strengthened my commitment to create positive change in my community and beyond.",
  },
  {
    slug: "ashley-makanaka-mazumba",
    name: "Ashley Makanaka Mazumba",
    institution: "Manicaland State University of Applied Sciences",
    email: "ashleymakanakamazumba@gmail.com",
    bio: "A God fearing young lady currently pursuing a degree in Metallurgical engineering. Apart from my academics, I'm passionate about serving the community through volunteer programmes and helping the needy. I'm also into cosmetic and girlie stuff selling.",
  },
  {
    slug: "atanga-brenda-esther-biboum",
    name: "Atanga Brenda Esther Biboum",
    institution: "University of Buea",
    email: "estherbrenda100@gmail.com",
    bio: "I am Atanga Brenda, a 5th-year medical student at the University of Buea, an aspiring cardiothoracic surgeon, and global health advocate. I believe Africa's challenges in healthcare and beyond are best solved through unity, one continent standing strong together. Beyond medicine, I'm a wellness advocate passionate about fitness and the gym, believing physical discipline fuels the resilience needed to drive real change.",
  },
  {
    slug: "ayorogo-david",
    name: "Ayorogo David",
    institution: "University of Ghana school of law.",
    email: "ayorogodavid14@gmail.com",
    bio: "Ayorogo is a postgraduate law student from Bolgatanga, in Ghana's Upper East Region, currently pursuing the Professional Law Course at the Ghana School of Law alongside an LL.M in Natural Resources Law at the University of Ghana Graduate School. Holding an LLB, his academic work spans petroleum and natural resources law, maritime law, water law, and professional legal practice, with particular depth in Ghana's upstream petroleum governance. He is driven by a passion for African development and the equitable distribution of the continent's natural resource wealth, with long-standing interests in land law and customary tenure. He is building toward a career in private legal practice focused on natural resources and petroleum law.",
  },
  {
    slug: "aziebong-maboh-gillian-ngeng",
    name: "Aziebong Maboh Gillian Ngeng",
    institution: "Catholic University of Cameroon Bamenda",
    email: "gillianngen@gmail.com",
    bio: "Aziebong Ngeng is a sixth-year medical student from Cameroon who is passionate about improving lives through healthcare, leadership, and meaningful conversations. She enjoys connecting with people from different backgrounds, learning from new perspectives, and creating opportunities for young people to grow. She believes that lasting impact comes from both serving individuals and working together to strengthen communities.",
  },
  {
    slug: "baang-riek-nhial",
    name: "Baang Riek Nhial",
    institution: "University of Juba",
    email: "bhangliethngool1999@gmail.com",
    bio: "Baang Riek Nhial I am a South Sudanese youth leader, peace advocate, and entrepreneur with a deep commitment to national development. I am currently a student at the University of Juba, where I have earned a Diploma in Natural Resource Management, while simultaneously advancing my studies as a 5th-term student in Business Administration at the University of the People. Balancing academics with activism, I am passionate about harnessing the potential of young people for peacebuilding and sustainable livelihoods. Through my entrepreneurial ventures and community engagement, I strive to bridge the gap between education and practical solutions for South Sudan's pressing social and economic challenges.",
  },
  {
    slug: "benedict-owusu-gyamfi",
    name: "Benedict Owusu Gyamfi",
    institution: "University of Ghana School of Law",
    email: "benedictgyamfi573@gmail.com",
    bio: "Benedict Owusu Gyamfi is an ambitious young man with a strong love for God and a desire for excellence. He is the second born of seven and loves his family. Benedict was the boys' prefect of World Link Academy where he had his basic education. He furthered his education at Achimota School after his excellent results in the Basic Education Certificate Examination. At Achimota School, he became the researcher for its writers and debaters' club, the General Secretary for Achimota Civic Education Club and was a member of the Students Entrepreneurship Club. He was also selected among the soccer team of the School, a reflection of his desire for an all-round building. On graduation from Achimota School, Benedict was awarded the Best Social Studies Student in SHS 2, the award for getting all As in the WASSCE, the overall best student in the Arts amongst others. In fact, at Achimota School, he had the merit list recognition after mock examinations. He gained admission to the University of Ghana to study Law where he is currently in his 3rd year. In the first year, he was elected a senator and enjoyed re-election until he decided to step down in the 3rd year. He also joined a student law firm, Lex Apex Associates where he is a researcher. The firm was awarded the 1st runner up for the major inter-firm moot court competition amongst 10 firms. Benedict has also participated in an Erasmus+ exchange programme in Germany where he was selected with 5 others to represent the school abroad despite its competitive nature. He is currently a member of the Sports Committee of the Law Students' Union and looks forward to being its head one day. He has interned with Kwame Boafo and Associates to gain practical experience in the legal field. He has also tutored during vacation at En-dor International School.",
  },
  {
    slug: "benjamin",
    name: "Benjamin",
    institution: "University of Rwanda",
    email: "ishibenj73@gmail.com",
    bio: "Benjamin Ishimwe is an applied mathematician and data science practitioner passionate about leveraging data to drive strategic decision-making in the financial sector. He currently serves as a Data Science Intern at the National Bank of Rwanda, where he specializes in credit risk modeling, credit scorecard simulations, and database management. Beyond his technical work, Benjamin is an active leader in civic and community development through Rotaract, where he leads as a service project chair of Rotaract club of Kigali Karisimbi. He is preparing to advance his technical expertise as an incoming Master’s student at Carnegie Mellon University Africa.",
  },
  {
    slug: "bridget-owuor",
    name: "Bridget Owuor",
    institution: "United States International University - Africa",
    email: "bridgetowuor8@gmail.com",
    bio: "Bridget Owuor is a business administration student with a passion for finance, economics, trade, and youth leadership. Her inspiration began as a YMAU IV delegate, where she gained firsthand experience in dialogue and collaboration, an opportunity that sparked her commitment to empowering young people. She believes financial literacy, inclusive trade, and sound economic policies are key to transforming communities and creating opportunities for youth. As a YMAU Ambassador, she is dedicated to amplifying young voices, fostering meaningful conversations, and inspiring positive changes through leadership, service, and continuous learning.",
  },
  {
    slug: "bright-benedict-agbeko",
    name: "Bright Benedict Agbeko",
    institution: "University of Ghana",
    email: "bagbeko45@gmail.com",
    bio: "I am Bright Benedict Agbeko, I am 19 years of age, a Ghanaian by birth and a student of the University of Ghana. I am currently in my third year studying Economics and Geography. I am an enthusiastic person who loves to reach out and connect with people as well as to share ideas. I love business and innovation",
  },
  {
    slug: "chimkachanma-chikezie",
    name: "Chimkachanma Chikezie",
    institution: "The African Leadership University",
    email: "kachanmachikezie@gmail.com",
    bio: "My name is Chimkachanma Chikezie and I am a first year student at the African Leadership University studying International business and trade. I am very passionate about diplomacy and advocacy for women and girls.",
  },
  {
    slug: "clarisse-iragena",
    name: "Clarisse Iragena",
    institution: "University of Rwanda",
    email: "iragenaclarisse1@gmail.com",
    bio: "I am a Governance and Development professional with a Bachelor's (Honours) degree in Governance Studies from the University of Rwanda. I have experience in public administration, journalism, communications, and stakeholder engagement through roles at Africana TV, CAO-Rwanda, and local government institutions. My expertise includes governance, policy analysis, advocacy, research, and strategic communication. I am passionate about promoting transparency, citizen participation, and sustainable development. With strong leadership, analytical, and communication skills, I aspire to advance public service delivery and contribute to impactful governance and development initiatives across Africa.",
  },
  {
    slug: "daniel-byiringiro",
    name: "Daniel Byiringiro",
    institution: "Ashesi University",
    email: "dbyiringiro@ashesi.edu.gh",
    bio: "Daniel Byiringiro is a Computer Science graduate from Ashesi University, Ghana. He currently serves as a Faculty Intern and AI Engineer in the CSIS Department, where he co-teaches Introduction to AI (CS 254) and builds a campus robotics platform (ARAP). He is a MasterCard Foundation Scholar Alumni and his work spans AI engineering, education technology, and applied research, including an AI grading pipeline combining Claude, Gemini, and GPT. Born into a refugee camp community with Rwandan heritage and raised in Zimbabwe, Daniel founded TWEENS, a peer education initiative at Tongogara Refugee Camp, and is now based in Accra, Ghana.",
  },
  {
    slug: "davine-uwase",
    name: "Davine Uwase",
    institution: "The African Leadership University",
    email: "d.uwase7@alustudent.com",
    bio: "I have always lived at the intersection of people and possibility. A national debate champion, writer, and former school council president, I have learned early that influence isn't given, it's earned through listening, clarity, and persistence. That instinct has carried me into Rwanda's fintech and startup world, where I've worn many hats: from pitching startups to hackathon wins, building retention strategies at a fast-growing fintech, and now thriving in the business development world. Along the way however, I developed a deep-seated passion for AI and its capabilities, and I'm now in my 2nd year of a software engineering degree. Part strategist, part storyteller, part builder, part leader, but I'm driven by one standard: showing up fully and making things better wherever I land.",
  },
  {
    slug: "deng-chol-bior-deng",
    name: "Deng Chol Bior Deng",
    institution: "United States international university Africa.",
    email: "dengc4278@gmail.com",
    bio: "My name is Deng Chol Bior Deng, a South Sudanese student pursuing a Bachelor of Science in Applied Computer Technology at USIU-Africa, currently in my second year. I proudly serve as the South Sudanese Students’ Representative for the 2025/2026 academic year, where I advocate for and support my fellow students. I am passionate about technology, leadership, and community development, with a strong commitment to learning, collaboration, and creating positive change through innovation and service. I aspire to use my skills and leadership experience to make a meaningful impact in my community and beyond.",
  },
  {
    slug: "diana-iradukunda-bazambanza",
    name: "Diana Iradukunda Bazambanza",
    institution: "University of Rwanda",
    email: "dianabazaira@gmail.com",
    bio: "Diana Iradukunda is a final-year Bachelor of Laws (LL.B.) student at the University of Rwanda with a passion for leadership, diplomacy, and youth empowerment. She serves as the Vice Chairperson of the University's Alternative Dispute Resolution (ADR) Club, where she promotes dialogue, mediation, and collaborative problem-solving among students. Diana participated in YMAU II Rwanda, an experience that strengthened her interest in African governance and international cooperation. She is also committed to legal research, community engagement, and advocating for opportunities that empower young people. Through her leadership and academic journey, she strives to contribute meaningfully to the development of Africa and inspire fellow youth to become active leaders in their communities.",
  },
  {
    slug: "elijah-edmund-nii-amon-kotey",
    name: "Elijah Edmund Nii Amon Kotey",
    institution: "Delhi Private school",
    email: "elijahkotey23@gmail.com",
    bio: "I am Elijah Kotey, an 18-year-old Ghanaian currently living in Accra. I love connecting with people, exploring new experiences, and finding humor in the little things around me. I have always been curious and adventurous. I love to research ,for instance i recently conducted research to see if I could fit two burgers in my mouth at the same. The findings are still under review.",
  },
  {
    slug: "elinam-tukpeyi",
    name: "Elinam Tukpeyi",
    institution: "International community school, Kumasi",
    email: "tdusena@gmail.com",
    bio: "My name is Elinam and I am a final year student of international community school. I am very passionate about m0del United Nations and have been to 6 conferences. I am excited to join the YMAU team and can’t wait to see all that’s in store this year.",
  },
  {
    slug: "eric-dufitimana",
    name: "Eric Dufitimana",
    institution: "Agahozo-Shalom Youth Village",
    email: "ericdufitimanaasyv@gmail.com",
    bio: "Watching my single mother come home past 11 every night instilled in me a desire to change the situation around me. This desire found an outlet when I became obsessed with fixing, opening, and inspecting old laptops and their spare parts. Consequently, my passion transitioned into coding as I began building projects, including our school’s career resources platform, which helps connect students to various opportunities. Through participating in YMAU, I got a glimpse of how technological advancements must be intertwined with effective diplomacy to be successful. As a 12th grader pursuing a career in computer science, I hope to become someone who bridges technology and diplomacy.",
  },
  {
    slug: "fani-banku-akan",
    name: "Fani Banku Akan",
    institution: "African Leadership University",
    email: "f.akan@alustudent.com",
    bio: "Fani Akan is an operational Management professional working at the intersection of Experiential learning and diplomatic tourism. she is on a mission to connect people, ideas, and opportunities across Africa. An award-winning delegate, Fani has represented institutions in diplomatic and policy simulations across the continent, earning recognition for her excellence in negotiation, leadership, and cross-cultural engagement.",
  },
  {
    slug: "fridaous-laleye",
    name: "Fridaous Laleye",
    institution: "United States International University-Africa",
    email: "fridaous354@gmail.com",
    bio: "Fridaous Laleye is a Mastercard foundation Scholar and Junior pursuing a Major in International Relations and a Minor in Integrated Studies at the United States International University-Africa. Having been actively involved in Model African Union Simulations as a chairperson, delegate, and Assistant Director over the last 3 years, she has developed a strong interest for debate on African policies, research on African affairs and for using her writing and oratory skills to advocate for reforms in the field of migration governance, education and peacebuilding on the continent.",
  },
  {
    slug: "frisca-kanadya-ramadanty",
    name: "Frisca Kanadya Ramadanty",
    institution: "Multimedia Nusantara University",
    email: "kanadyafrisca@gmail.com",
    bio: "Biography I am a passionate individual with a strong interest in international relations, diplomacy, and global affairs. One of the ways I pursue this passion is through Model United Nations (MUN), where I enjoy representing different countries, researching international issues, and participating in debates on global challenges. MUN has helped me strengthen my public speaking, critical thinking, negotiation, and teamwork skills while broadening my understanding of international cooperation. I am particularly interested in topics such as peace and security, sustainable development, human rights, and global governance. Beyond conferences, I actively follow world events and enjoy learning about different cultures and political systems. I believe that meaningful dialogue and collaboration are essential for solving complex global problems. Through my continued involvement in MUN, I hope to develop the knowledge, leadership, and communication skills needed to make a positive contribution to the international community and inspire others to engage in global issues.",
  },
  {
    slug: "gael-imena",
    name: "Gael Imena",
    institution: "Equity Leaders Program",
    email: "imenagael@gmail.com",
    bio: "I am Gael IMENA and previously served as the president for equity leaders program cohort 4. It’s a program that selects Rwandas top performing students and offers them internships in Equity Bank Rwanda and it was truly transformative. Aside from that I like reading, am a football fanatic, and I enjoy playing instruments too!",
  },
  {
    slug: "gaella-impundu",
    name: "Gaella Impundu",
    institution: "International Leadership University",
    email: "impundubeniegaella@gmail.com",
    bio: "My name is Gaella, I am passionate about education and women empowerment. That is the reason why I am taking part in initiatives that teach young girls in highschool core subjects such as chemistry, English, to prepare them for University. Specifically, tutor maths",
  },
  {
    slug: "garang-joseph-thon",
    name: "Garang Joseph Thon",
    institution: "University of Juba",
    email: "garangjosephthon19@gmail.com",
    bio: "Born in South Sudan as a war child, I started my education in Uganda before returning home to finish high school. Now in my fourth year studying Computer Science and IT at the University of Juba, I combine my tech skills with a passion for creative media through my brand, Genius Mind Pro. Deeply rooted in my faith and church community, I'm dedicated to giving back by promoting youth sports, grassroots innovation, and digital outreach. My journey drives me to use technology and service to help build a brighter, more connected future for my community.",
  },
  {
    slug: "gloria-miyoma-bon",
    name: "Gloria Miyoma Bon",
    institution: "St. Paul's University",
    email: "miyoma.bon@gmail.com",
    bio: "Gloria Bon is an award-winning diplomatic leader bridging technology, governance, and youth advocacy across Africa. With academic background in Business and Information Technology, she translates complex policy into actionable recommendations that center young women and girls. She was honored as Overall Best Fellow in the 2025 Girls In Diplomacy Fellowship and as an Outstanding Delegate at the Yale Model African Union IV. She currently serves as Inaugural Chair of the GID Alumnae Council, pioneering governance frameworks for alumnae engagement. Her experience spans executive-level policy support in Kisumu County and global advocacy with Theirworld (UK). A fellow of Aspire, Kectil, LEAP, and Amazon Leadership programs, Gloria is deeply committed to digital inclusion, cybersecurity governance, and gender-equitable policy across Africa.",
  },
  {
    slug: "grace-cindy-kah-nguti",
    name: "Grace Cindy Kah-Nguti",
    institution: "School of Health and Medical Sciences, Catholic University of Cameroon (SHMS-CATUC), Bamenda",
    email: "gracenguti95@gmail.com",
    bio: "I am a 6th year medical student currently pursuing a degree of Doctor of Medicine, passionate about democracy and leadership shaping Cameroon and Africa for a better world",
  },
  {
    slug: "hamdallah-alhassan",
    name: "Hamdallah Alhassan",
    institution: "United States International University-Africa",
    email: "hamdallahalhassan68@gmail.com",
    bio: "Hamdallah Alhassan is a third-year Applied Computer Technology student at the United States International University-Africa (USIU-A) in Kenya and a Mastercard Foundation Scholar. She is passionate about technology, youth empowerment, and community development. Hamdallah has been involved in leadership and community initiatives, including attending the YALI Model African Union (YMAU) at USIU-A in May 2025. She has supported youth-focused initiatives through Get Impeccable, contributing to efforts that connect young people with career development opportunities. He also volunteers as a Web Development Lead at Nexo Girls, where he supports the development of digital solutions that promote girls' empowerment. Beyond technology, Hamdallah is committed to education and mentorship. Through Angaza Center, she tutors high school students in Kenya, helping them strengthen their academic skills and encouraging them to pursue their educational goals. Through his academic journey, volunteer experiences, and leadership involvement, Hamdallah continues to explore how technology, education, and collaboration can be used to create opportunities and positively impact communities.",
  },
  {
    slug: "hania-jalila-efisia-windsom",
    name: "Hania Jalila Efisia Windsom",
    institution: "International School of Ouagadougou",
    email: "h.kafando@iso.bf",
    bio: "My name is Hania Jalila Efisia Windsom Kafando and I am an international student from Burkina Faso. I am passioned in mathematics, leadership and arts. I enjoy a good academic challenge while also taking pleasure into activities like painting of designing. I am never tired of learning and exploring new options. I always force myself to get out of my comfort zone and try to leave an impact everywhere I go. YMAU V is the place where I discovered my interest for youth engagement. I look forward to empowering other young people and sharing those new opportunities.",
  },
  {
    slug: "helga-kemunto",
    name: "Helga Kemunto",
    institution: "University of Nairobi",
    email: "helganyagwoka@gmail.com",
    bio: "Hi, my name is Helga Kemunto. I was born in Molo, Nakuru county, Kenya and currently reside in Kiserian, Kajiado county, Kenya. I completed my highschool education in 2023 after attending Loreto high school, Limuru, Mt St Mary's primary school for my primary education and St Francis Montessori for my pre primary. I am currently a third year Veterinary student at the University of Nairobi, was a world scholar in 2023 , where I debated upto the Global level in London. I am a PR rep for 2 student organizations and I love meeting new people and connecting with them.",
  },
  {
    slug: "janiqua-frimpong-boateng",
    name: "Janiqua Frimpong-Boateng",
    institution: "International Community School",
    email: "jajanimeclub@gmail.com",
    bio: "Hi! I'm a student from Ghana who loves meeting new people, trying new things, and finding ways to make a positive impact wherever I can. I'm naturally curious, enjoy taking on leadership opportunities, and love being part of conversations that bring people together. Whether I'm working on a school project, helping organize an event, or simply encouraging others, I always try to bring energy, kindness, and a positive attitude. I'm excited about opportunities like YMAU because they allow me to learn, grow, and connect with amazing young people from across Africa.",
  },
  {
    slug: "jeremiah-chisomaga-ugochukwu",
    name: "Jeremiah Chisomaga Ugochukwu",
    institution: "Soka University of America",
    email: "jeremiahugochukwu384@gmail.com",
    bio: "Jeremiah Ugochukwu is an aspiring diplomat and international attorney studying International Studies on a pre-law track at Soka University of America. Passionate about Pan-Africanism, he has a strong background in environmental advocacy, alongside Model AU and Model UN simulations. Jeremiah is an EducationUSA Opportunity Funds Program scholar and has served as a Youth Advisor for World Ocean Day. Currently, he works with the CGSS department at USM in Malaysia to promote sustainability. As a YMAU Ambassador, Jeremiah applies systems thinking to global policy and diplomacy.",
  },
  {
    slug: "john-ngor-deng-garang",
    name: "John Ngor Deng Garang",
    institution: "Sciences Po",
    email: "johnngordeng.garang@sciencespo.fr",
    bio: "John Garang is a Media and Communications Professional with experience in marketing, storytelling, and digital communication across Africa. With over four years in the media and communications industry, he uses creative storytelling for social impact. John holds a BSc in Entrepreneurial Leadership from the African Leadership University and is pursuing an MA in Communications, Media, and Creative Industries at Sciences Po. He is passionate about education, youth empowerment, and digital innovation. Outside work, he enjoys poetry, photography, mentoring young people.",
  },
  {
    slug: "kehinde-john-okunade",
    name: "Kehinde John Okunade",
    institution: "University of Ibadan",
    email: "okunadekehindejohn@yahoo.com",
    bio: "Kehinde John Okunade is a final-year Linguistics student at the University of Ibadan, Nigeria, and a passionate advocate for youth leadership and sustainable development across Africa. He is the Founder and Executive Director of The Impact Rise Global and the founder of LinguaRise Africa, an organization dedicated to making the science of language accessible to all. A proud alumnus of YMAU V in Ghana, Kehinde is deeply committed to international relations, climate advocacy, and empowering the next generation of African diplomats through community engagement and cross-border collaboration.",
  },
  {
    slug: "keren-happuc-eberechukwu-nwabuike",
    name: "Keren-Happuc Eberechukwu Nwabuike",
    institution: "International University of Grand-Bassam",
    email: "nwabuikek1@student.iugb.edu.ci",
    bio: "Keren-Happuc NWABUIKE is a Mechanical Engineering and Petroleum Technology student at the International University of Grand-Bassam (IUGB), driven by innovation, leadership, and excellence. She currently serves as a Maintenance Intern at SLB, gaining hands-on experience in the energy industry while strengthening her technical expertise. Her leadership journey includes serving as Chief Diversity Officer of the SGA and General Secretary of the She Club, where she championed diversity, inclusion, student engagement, and youth empowerment through impactful initiatives. Alongside her engineering journey, she is a commercial model who confidently represents brands with professionalism and creativity.Driven by a problem-solving mindset, Keren-Happuc combines academic achievement, practical experience, and strong communication skills to inspire positive change. She is committed to building impactful solutions that improve lives ,empower communities, and shape a more sustainable, inclusive , and prosperous future.",
  },
  {
    slug: "konadu-micheal",
    name: "Konadu Micheal",
    institution: "University of Ghana",
    email: "konadumicheal43@gmail.com",
    bio: "Dedicated social work and sociology student at the university of Ghana with a proven track record of leadership and community service. Passionate about socio- economic development, youth empowerment, and strategic utilization of national resources for job creation. Experienced in data management and public relations through high-stakes roles with the Electoral Commission of Ghana. Committed to fostering civic engagement and developing infrastructure that supports emerging young leaders.",
  },
  {
    slug: "konan-banny-maguy-anne-marie-jennifer-elmirah",
    name: "Konan-Banny Maguy Anne-Marie Jennifer Elmirah",
    institution: "International University of Grand-Bassam",
    email: "konan-bannym1@student.iugb.edu.ci",
    bio: "Maguy Konan Banny is a Business Administration (Economics) student at the International University of Grand-Bassam in Côte d’Ivoire. She is passionate about youth empowerment, education, and economic development in Africa. Curious and driven, she enjoys learning, conducting research, and exploring ideas that can create lasting impact in her community. As a YMAU Ambassador, she is excited to connect with young leaders from across the continent, contribute to meaningful initiatives, and continue growing as a leader committed to positive change.",
  },
  {
    slug: "krystal-gibbs-muloni",
    name: "Krystal Gibbs Muloni",
    institution: "West Nairobi School",
    email: "krstlgbs@gmail.com",
    bio: "Krystal is a driven high school student, entrepreneur, and youth leader based in Nairobi, Kenya. As a newly selected YMAU VI Ambassador, she is honored to represent her community while collaborating with young leaders across Africa. Passionate about creating positive change, she founded One Meal More, a youth-led initiative dedicated to serving local communities. She also creates digital content that encourages creativity and personal growth. With aspirations to study business and become a global entrepreneur, Krystal is excited to serve as a YMAU VI Ambassador by connecting with young leaders, promoting meaningful initiatives, and inspiring others to make a difference.",
  },
  {
    slug: "lamine-musa-bamba",
    name: "Lamine Musa Bamba",
    institution: "African Methodist Episcopal University",
    email: "laminembamba5@gmail.com",
    bio: "Lamine Musa Bamba is a student living in Liberia, born on September 13, 2004. He is a hardworking, friendly, and honest young leader passionate about leadership, volunteering, community service, and youth engagement. ‎ ‎Lamine is committed to contributing to the development of his community and promoting the African continent. He believes in the power of young people to create positive change and is dedicated to seeking practical solutions to the challenges facing Africa. ‎ ‎Through his passion for service and leadership, he hopes to inspire others and contribute to building a better future for his community and the continent. ‎ ‎",
  },
  {
    slug: "leslie-keli-tunu",
    name: "Leslie Keli Tunu",
    institution: "Ghana Christian International High School",
    email: "tunukekeli@gmail.com",
    bio: "My name is Leslie Tunu, a Ghanaian high schooler specializing in the sciences. My curiosity has carried me well beyond the classroom, earning distinctions across a range of co- and extracurricular pursuits in Science, Mathematics, and writing. It was through Model United Nations that I discovered my passion for diplomacy and advocacy, and in that process, I came to see clearly the barriers to socioeconomic mobility that connect young people across the African continent. That realization has shaped my sense of purpose. I believe technology is a bridge toward shared progress, so I've taught myself several programming languages to build projects designed to ease the everyday lives of Africans, wherever they call home on the continent.",
  },
  {
    slug: "lisungu-maggie-chirwa",
    name: "Lisungu Maggie Chirwa",
    institution: "Curtin University",
    email: "lisungumchirwa@gmail.com",
    bio: "Lisungu Maggie Chirwa is an incoming Civil Engineering student at Curtin University from Malawi. Passionate about community development through charity, volunteering, entrepreneurship, and diplomacy, she serves as a YMAU VI Ambassador. After finding her own experience with the Yale Model African Union deeply eye-opening, Lisungu is highly motivated to give back by providing guidance and assistance to prospective delegates looking to attend the program.",
  },
  {
    slug: "mariamsira-meseret-wondim",
    name: "Mariamsira Meseret Wondim",
    institution: "Gibson school Systems",
    email: "marroomest@gmail.com",
    bio: "Mariamsira Meseret is a recent graduate of Gibson School Systems with a passion for international diplomacy and global health equity. A proven leader and academic achiever, she represented Egypt as a delegate at the Yale Model African Union, served as a senate leader in her sophomore year and club president in junior year and secured first place in regional academic quiz bowl, science fair and math competition. She aims to merge cross cultural communications with scientific inquiry as she is fluent in multiple languages. Mariamsira is geared towards studying medicine as she is aiming to actively support sustainable development across Africa and collaborative health care solutions.",
  },
  {
    slug: "matthew-muathime-musembi",
    name: "Matthew Muathime Musembi",
    institution: "African Leadership University - Rwanda",
    email: "m.musembi1@alustudent.com",
    bio: "Matthew Muathime is an entrepreneur, leader and creative professional passionate about leveraging innovation to solve Africa's most pressing challenges. He is the Founder and CEO of CareNest, a digital maternal healthcare platform that aims to reduce maternal and neonatal mortality in Rwanda and across Africa by addressing one of the most persistent challenges in maternal healthcare: fragmented and inaccessible patient data. He is also a professional voice-over artist dedicated to amplifying African stories and promoting a positive narrative about the continent. He currently serves as the May 2025 Intake Representative at ALU, Marketing Vice President of AIESEC in Rwanda and Yale Model African Union Ambassador, where he champions leadership, collaboration and youth development. Committed to continuous growth, he actively seeks opportunities to expand his skills while creating meaningful social impact.",
  },
  {
    slug: "mbabazi-justine-tasha",
    name: "Mbabazi Justine Tasha",
    institution: "University of Rwanda",
    email: "justinembabazi44@gmail.com",
    bio: "I have agood personality no bad back group hardworking pertionate understanding",
  },
  {
    slug: "miencloe-jatniel-anais-kouakou",
    name: "Miencloé Jatniel Anaïs Kouakou",
    institution: "International University of Grand Bassam",
    email: "kouakoum5@student.iugb.edu.ci",
    bio: "I am a fourth-year Mathematics student specializing in Actuarial Science at the International University of Grand-Bassam, in Côte d'Ivoire. I am passionate about leadership, diplomacy, and youth empowerment. My analytical mindset, strong communication skills, adaptability, and collaborative spirit enable me to connect with and inspire others. Participating in YMAU V strengthened my interest in policy dialogue and African development. As a regional Ambassador, I am eager to promote YMAU's mission, encourage student participation, and help build a community of informed, ethical, and visionary young leaders.",
  },
  {
    slug: "miendjiem-kemo-hilary-segolene",
    name: "Miendjiem Kemo Hilary Ségolène",
    institution: "Université des Montagnes",
    email: "segolenehilary@gmail.com",
    bio: "MIENDJIEM KEMO Hilary Ségolène is a seventh-year medical student at Université des Montagnes, Cameroon, with a deep interest in global health, public health policy, and health diplomacy. As Director of the Standing Committee on Social Security for Medical Students (SCOCM) within CAMSA, she drives strategic partnerships and advocates for student welfare. Recognized with an Honorable Mention at the Youth Model African Union V conference in Accra, Hilary is a passionate champion for mental health advocacy, gender equality, and youth leadership. As a YMAU Ambassador, she remains dedicated to bridging clinical medicine and transformative, youth-led policy across Africa.",
  },
  {
    slug: "mohamed-emad-abdelfatah",
    name: "Mohamed Emad Abdelfatah",
    institution: "Saint George International School",
    email: "mohamedeemad100@gmail.com",
    bio: "I am a high school student passionate about international relations and political science, with a strong commitment to youth empowerment and global collaboration. I founded Diplomind, a youth-led non-profit organization that empowers young people through diplomacy, psychology, and leadership while advancing the UN Sustainable Development Goals. My academic interests also extend to interdisciplinary research, where I have conducted research in both medicine and cultural studies. Through my work, I strive to bridge knowledge across disciplines and create meaningful impact in my community and beyond.",
  },
  {
    slug: "mohammed-y-konneh",
    name: "Mohammed Y Konneh",
    institution: "University of Liberia (UL)",
    email: "mvmkonneh@gmail.com",
    bio: "Mohammed Y. Konneh is a junior Biomedical Science student at the University of Liberia with a strong interest in medical research, public health, and youth leadership. He has demonstrated academic excellence while actively serving in leadership and community initiatives, including the University of Liberia Muslim Students' Association (ULMSA) and the Brothers Forever organization. Mohammed also participated in the YMAU Africa Union Conference in Ghana, where he strengthened his skills in diplomacy, policy, and leadership. Passionate about innovation and service, he is committed to advancing healthcare, empowering young people, and contributing to evidence-based solutions that improve the well-being of communities in Liberia and beyond.",
  },
  {
    slug: "moses-afolayan",
    name: "Moses Afolayan",
    institution: "Lagos University Teaching Hospital",
    email: "mosesafolayan1@gmail.com",
    bio: "I am medical doctor public health researcher, and health policy advocate passionate about strengthening health systems across Africa. His work spans epidemiology, health financing, disease surveillance, and implementation research, with experience supporting public health programs in Nigeria. He has presented research at international conferences and is committed to translating evidence into policy and practice. I am passionate about youth leadership, global health diplomacy, and empowering young Africans to drive sustainable development through collaboration, innovation, and evidence-based decision-making.",
  },
  {
    slug: "mukamugisha-esther",
    name: "Mukamugisha Esther",
    institution: "University of Rwanda",
    email: "mukamugishaesther08@gmail.com",
    bio: "Mukamugisha Esther is a Creative and Performing Arts student at the University of Rwanda and a Mastercard Foundation Scholar. She is a young leader passionate about education, youth empowerment, environmental sustainability, innovation, and social justice. Through leadership fellowships, volunteer service, and community initiatives, she has developed skills in advocacy, project management, entrepreneurship, and creative storytelling. Esther has contributed to programs that empower young people, promote inclusive development, and encourage innovative solutions to community challenges. She is committed to using creativity and leadership to inspire positive change and build stronger, more inclusive communities across Rwanda and beyond.",
  },
  {
    slug: "musa-sekou-sheriff",
    name: "Musa Sekou Sheriff",
    institution: "United Methodist university",
    email: "sheriffmusasekou@gmail.com",
    bio: "Musa Sekou Sheriff is a young Liberian leader, educator, and advocate for youth empowerment. Born and raised in Liberia, he is a Muslim and belongs to the Mandingo ethnic group. He graduated from Salafiya Grammar High School and is currently pursuing a bachelor’s degree in Biology and Chemistry at United Methodist University. Driven by a passion for learning and community development, Musa has continued to build his knowledge and leadership capacity through various educational and professional development opportunities. He earned a certificate in Computer Literacy and later participated in the African Leadership Academy, where he strengthened his leadership skills and broadened his understanding of community service and positive social impact. Musa is widely recognized for inspiring young people to believe in themselves, pursue education, and become responsible leaders who contribute meaningfully to society. He is committed to mentoring youth and encouraging them to develop the knowledge, discipline, and values needed to build a brighter future. His passion for education has always motivated him to build strong networks of vibrant communities, promote lifelong learning, and empower others through leadership, collaboration, and service. Musa believes that education is the foundation for personal growth and national development, and he remains dedicated to creating opportunities that help young people reach their full potential.",
  },
  {
    slug: "nancy-adama-mansaray",
    name: "Nancy Adama Mansaray",
    institution: "Kofi Annan Universite De Guineè",
    email: "bbynancymans@gmail.com",
    bio: "An exceptionally decorated Diplomacy scholar and native English-speaking professional specializing in institutional protocol, large-scale project management, and corporate administration. Proven track record founding advocacy organizations, directing international student bodies, executing complex external embassy logistics, and managing compliance workflows for regional youth platforms. Recognized across West Africa with multiple \"Best Delegate\" distinctions for negotiation excellence; equipped with high emotional intelligence (EQ) and exceptional structural discipline to drive operational impact.",
  },
  {
    slug: "ndayishimiye-david",
    name: "Ndayishimiye David",
    institution: "University of Rwanda",
    email: "ndayishimiyedavid3@gmail.com",
    bio: "David Ndayishimiye is a human rights advocate and agricultural innovator dedicated to community resilience. Born in Minembwe, DRC, to the Banyamulenge community, he was raised in Rwanda and is currently pursuing a degree in Crop Production at the University of Rwanda, Busogo Campus. Following his transformative experience at YMAU VI, David actively campaigns against the systemic persecution of his people, notably co-organizing the #BanyamulengeCantBreathe movement , which successfully secured Red Cross medical interventions. Combining his passion for human rights with his background in agricultural technology, branding and Graphic designing, David strives to empower marginalized communities and amplify student voices.",
  },
  {
    slug: "nelly-munjanja",
    name: "Nelly Munjanja",
    institution: "University of South Africa",
    email: "munjanjanelly2003@gmail.com",
    bio: "Nelly is an aspiring diplomat and policymaker passionate about addressing socio-economic inequalities on a global scale. Her long-term goal is to qualify as a Chartered Accountant and leverage her financial expertise to inform effective, equitable, and sustainable policy decisions. Currently undergoing Chartered Accountancy training as an Audit Assistant, she is developing a strong foundation in financial reporting, governance, and accountability. Beyond her professional training, she actively participates in African Union simulation conferences to deepen her understanding of diplomacy, international relations, and policymaking. She is eager to contribute to spaces where finance, policy, and social impact intersect, and to build a career that drives meaningful change.",
  },
  {
    slug: "ngobesing-lum-raina-braine",
    name: "Ngobesing Lum Raina-Braine",
    institution: "Catholic University of Cameroon (CATUC) Bamenda",
    email: "rainabraine5@gmail.com",
    bio: "Ngobesing Lum Raina-Brains is a sixth-year medical student from Cameroon, health communicator, and founder of Mental Vitality, a digital platform advancing mental health education and awareness across Africa and beyond. Passionate about mental health, public health, and community impact, she has contributed to digital health content, and community change by volunteering in multiple organizations including CAMSA, REACT Cameroon, REACH, Sexual Health Companion and MedCamer. She is committed to making health information accessible, culturally relevant, and stigma-free, and hopes to use medicine, media, and advocacy to improve health equity and inspire positive change.",
  },
  {
    slug: "ngong-claris-nain",
    name: "Ngong Claris Nain",
    institution: "Catholic university of Cameroon",
    email: "clarisnain2@gmail.com",
    bio: "I am NGONG Claris NAIN, a licensed nurse, health advocate, and passionate youth leader from Cameroon. I am committed to improving health outcomes through leadership, community engagement, and health education. My work focuses on empowering young people, promoting sustainable development, and advocating for equitable healthcare across Africa. As a YMAU Ambassador, I am proud to represent a network of changemakers dedicated to inspiring collaboration, innovation, and positive impact. I believe that service, compassion, and collective action are powerful tools for building healthier, stronger, and more resilient communities.",
  },
  {
    slug: "nikiema-axelle-hadassah-barkwende",
    name: "Nikiema Axelle Hadassah Barkwende",
    institution: "International school of Ouagadougou",
    email: "ax.nikiema@iso.bf",
    bio: "am a Burkinabè girl, born and raised in Burkina Faso until the age of eight. I began my education in a national private school before moving to the Republic of Congo with my siblings after my mother received a job there. For five years, I attended an American international school, receiving an English-speaking education in a multicultural environment. I later returned to Burkina Faso to live with my father while my mother worked in Mali. I continued my education at an international school, where I developed a broader worldview while reconnecting with my roots and culture.",
  },
  {
    slug: "nimotallahi-raji",
    name: "Nimotallahi Raji",
    institution: "University of Ibadan",
    email: "nimotraji@gmail.com",
    bio: "Nimotallahi Raji is a Food Technology graduate from the University of Ibadan, passionate about advancing sustainable food systems through research, policy, diplomacy and youth leadership. She is particularly interested in reducing post-harvest losses and promoting meaningful youth participation in shaping food systems across Africa. Having previously participated in the Yale Model African Union Conference, she experienced firsthand the value of youth engagement, collaboration and policy dialogue. She looks forward to helping more young people discover and benefit from the opportunities YMAU offers while encouraging them to become active contributors to Africa's development.",
  },
  {
    slug: "oluwadamilola-selome-jacobs",
    name: "Oluwadamilola Selome Jacobs",
    institution: "African Leadership University",
    email: "o.jacobs@alustudent.com",
    bio: "Oluwadamilola Jacobs is a Programs Strategist, venture builder, and social impact advocate passionate about entrepreneurship, youth development, and community building across Africa. She has experience in program design, partnerships, strategic operations, and supporting entrepreneurs through her work at African Leadership University. She is also the founder of Ìsinmi, a social impact initiative focused on creating pathways to rest and support for survivors of sexual assault in Nigeria. A passionate advocate for dialogue and diplomacy, Oluwadamilola is a proud alumna of the Yale Model African Union, where she was recognized as an Outstanding Delegate at YMAU IV. She is excited to serve as a YMAU Ambassador.",
  },
  {
    slug: "promise-oladejo",
    name: "Promise Oladejo",
    institution: "Obafemi Awolowo University",
    email: "promiseoladejo@gmail.com",
    bio: "Promise Oladejo is a fifth-year nigerian medical student who is fascinated by how better policies and better technology can improve the way healthcare works. His interests span digital health, health policy, and health systems strengthening, with a particular focus on making healthcare more accessible and responsive across Africa. Beyond the classroom, he has led health education initiatives reaching over 2,500 young people and participated in conversations on health innovation and governance through platforms such as the Yale Model African Union and the Africa Digital Health Summit. He enjoys connecting people, ideas, and opportunities that improve health.",
  },
  {
    slug: "roger-manara-israel",
    name: "Roger Manara Israel",
    institution: "UNIVERSITY OF GOMA",
    email: "manararogerisrael@gmail.com",
    bio: "Final-year Master's student in Communication, Education, and Development Studies at the University of Goma (DRC), I am a peacebuilder, climate advocate, and sustainability leader committed to driving community-led transformation. As Founder & Executive Chair of Green Hope Initiative for Development (GHID) and CEO of the International Green Centre, I have led impactful initiatives advancing peacebuilding, youth leadership, and environmental resilience across eastern Democratic Republic of Congo. Since founding GHID in 2022, I have worked alongside more than 2,500 young volunteers and displaced women to promote peace, strengthen leadership, and foster environmental stewardship while empowering local communities. My leadership has earned international recognition, including participation in COP29 in Azerbaijan, where I contributed to global climate dialogue. I have also served as a former Ambassador for the Rockefeller Foundation and EarthX, championing youth-driven solutions for sustainable development. Through strategic communication, innovation, and grassroots action, I am dedicated to inspiring the next generation of changemakers and building more peaceful, resilient, and sustainable communities.",
  },
  {
    slug: "samuel-amissah",
    name: "Samuel Amissah",
    institution: "University of Ghana",
    email: "samuelamissah0519@gmail.com",
    bio: "Short Biography Samuel Amissah is a promising law student at the University of Ghana School of Law (UGSOL). He currently serves as Justice of the Judicial Board of Alexander Kwapong Hall and President of the University of Ghana chapter of the PLO Lumumba Foundation Mentee Club. Passionate about leadership, research, and justice, Samuel is also preparing for an ambassadorial role with YMAU. He is deeply committed to mentorship, youth empowerment, and legal excellence. (68 words)",
  },
  {
    slug: "samuel-fodop",
    name: "Samuel Fodop",
    institution: "Catholic University of Cameroon",
    email: "samuelfodop04@gmail.com",
    bio: "Fodop is a multi-award-winning Cameroonian medical student with a strong commitment to research, leadership, and diplomacy. He has authored several peer-reviewed publications and presented at major scientific conferences across Africa. He recently began a journey in diplomacy, sparked by his participation in the Yale Model African Union in Nairobi and Accra, convened by Yale University, where he discovered the vital role of youth in shaping African policies. Owing to his brilliance, he received the Kofi Annan Award for collaborative state and leadership at the 5th Yale Model African Union Conference in Ghana.",
  },
  {
    slug: "samuel-irakoze",
    name: "Samuel Irakoze",
    institution: "University of BURUNDI",
    email: "samuelirakoze74@gmail.com",
    bio: "Samuel Irakoze is a passionate youth leader and advocate from Burundi dedicated to leadership, peacebuilding, environmental sustainability, and human dignity. He is the Founder of the Human Respect Leadership Academy (HRLA), a Representative of Burundi Association For Life serving as a Lifesaver at Campus Rohero, an active member of the World Peace Initiative, the African Youth Leadership Forum, and an activist with Africa Youth Green Environment. Through these roles, he empowers young people, promotes civic engagement, and works to build peaceful, inclusive, and sustainable communities in Burundi and across Africa.",
  },
  {
    slug: "seblewongel-girma-bayu",
    name: "Seblewongel Girma Bayu",
    institution: "Model Africa Union Ethiopia",
    email: "seblewongelgirma666@gmail.com",
    bio: "Seblewongel Girma Bayu is a technology entrepreneur and social impact advocate serving as Co-Founder & COO of Vintage Technologies PLC. She is also the Clubs Director of Model African Union Ethiopia and served as Chairperson of Model African Union Ethiopia’s AU–EU Summit Model 2026 recently. She earned recognitions including the Honorable Delegate Award from MAU Ethiopia and Best Delegation Award to Ethiopia at the Best Diplomats Conference in Istanbul, Turkey. She is passionate about women empowerment, youth leadership, and creating opportunities through innovation.",
  },
  {
    slug: "selby-mashiki",
    name: "Selby Mashiki",
    institution: "National University of Science and Technology",
    email: "mashikiselby@gmail.com",
    bio: "I am an Information Management and Technology student at the National University of Science and Technology (NUST), Zimbabwe, with a strong passion for Linux, cybersecurity, artificial intelligence, and open-source software. I founded Aethar Tech and developed OmegaOS, an offline-first Linux distribution designed to improve digital access in low-connectivity environments. I enjoy building practical technology solutions, contributing to open-source projects, and exploring innovative ways to use technology to solve real-world challenges across Africa.",
  },
  {
    slug: "sennedy-arhinful",
    name: "Sennedy Arhinful",
    institution: "University of Ghana",
    email: "asennedy@gmail.com",
    bio: "Sennedy Arhinful is a Research Fellow at the Centre for Advanced and Applied Research (CAAR) with strong interests in climate change and environmental sustainability, governance and social policy, and artificial intelligence. A dedicated youth and student leader, he brings extensive experience in purposeful leadership and advocacy, particularly in peacebuilding, mental health, youth development, and access to quality education. Serves as a volunteer facilitator with Edify Ghana, where he delivers the Made for More leadership training in basic schools across Ashaiman. His work champions ethical, Christlike leadership and community service. Beyond his leadership and advocacy roles, Sennedy is a prolific reader and writer, committed to advancing knowledge and inspiring positive change.",
  },
  {
    slug: "setayesh-fakhrtavoli",
    name: "Setayesh Fakhrtavoli",
    institution: "International University of Grand-Bassam",
    email: "fakhrtavolis1@student.iugb.edu.ci",
    bio: "My name is Setayesh Fakhrtavoli, and I am a senior studying Political Science and International Relations at the International University of Grand-Bassam, where I continue to explore my passion for diplomacy, leadership, and social impact. I have always found myself between cultures, conversations, and communities. As an Iranian student in Côte d’Ivoire, I have grown to appreciate the power of diversity and the importance of creating connections between people from different backgrounds. Curious, adaptable, and passionate about bringing people together, I enjoy creating spaces where ideas are exchanged, perspectives are challenged, and young people feel empowered to make a difference.",
  },
  {
    slug: "shingai-d-zhumu",
    name: "Shingai D. Zhumu",
    institution: "Fidelity Life Medical Aid Society",
    email: "dalezhumu35@gmail.com",
    bio: "I'm a marketing professional with 5 years under my belt, a public speaker, a wellness coach, and a proud Rotarian and honestly, those four things feed each other more than people expect. Marketing taught me how to tell a story people actually care about. Speaking taught me how to say it out loud without losing the room. Coaching taught me that growth isn't just a business metric, it's personal, and it takes patience. And Rotary reminds me every week why any of this matters: real impact happens in community, not in a campaign report. So if you're wondering what I actually do, I help people and brands show up as their best, clearest selves. Sometimes that's a marketing strategy. Sometimes it's a talk on stage. Sometimes it's a coaching conversation that has nothing to do with business at all. And sometimes it's just showing up to serve, because that's where it all comes full circle for me. I believe good marketing sounds human, good speaking feels like a conversation, good coaching meets people where they are, and good service asks for nothing back. That's the thread running through everything I do.",
  },
  {
    slug: "sinqobile-caren-dube",
    name: "Sinqobile Caren Dube",
    institution: "National University of Science and Technology, Bulawayo",
    email: "sinqobilemthembo@gmail.com",
    bio: "A third year computer science student at the National University of Science and Technology (Zimbabwe), a fulltime software developer intern at Mviyo Technologies, a part-time robotics mentor for the World Robot Olympiad, and the technical lead for Google Developers NUST chapter as well as an academic researcher in intelligent systems. Apart from computers and technologies, I am also passionate about people, their voices, opinions, and rights. Expectedly, I also happen to find fascination in leadership, systems of power and leadership structures, and how everything (economies, societies, fairness, education, e.t.c) rises and falls by it.",
  },
  {
    slug: "tadiwanashe-heather-natasha-chibonda",
    name: "Tadiwanashe Heather Natasha Chibonda",
    institution: "National University of Science and Technology (NUST)",
    email: "tadiwanashechibonda@gmail.com",
    bio: "Tadiwanashe Heather Natasha Chibonda is an Informatics undergraduate at the National University of Science and Technology in Zimbabwe, dedicated to bridging the digital divide through grassroots hardware innovation. As Brand and Community Lead for the NUST CyberHub and a passionate STEM mentor, she champions cybersecurity and sustainable technology. Tadiwanashe actively empowers marginalized youth and young women to transition from passive technology consumers into active digital architects. Having built localized solutions like the \"MyMukando\" fintech platform and \"Health On the Go\" telehealth system, she strives to cultivate a youth-driven, inclusive tech ecosystem across Southern Africa.",
  },
  {
    slug: "tinashe-chikuvira",
    name: "Tinashe Chikuvira",
    institution: "Zimbabwe National Defence University",
    email: "xtinashe12@gmail.com",
    bio: "Tinashe Chikuvira is an Electrical and Electronics Engineering student passionate about advancing green technologies to drive sustainable development in Zimbabwe. He is deeply interested in leadership, diplomacy, and creating solutions that address Africa's energy challenges. A social and culturally curious individual, Tinashe enjoys connecting with people from diverse backgrounds and aspires to leave his footprints across every corner of Africa. He is a dedicated hockey and chess player, a family-oriented individual, and proudly served as one of the pioneers of the first-ever iteration of the Yale Model African Union.",
  },
  {
    slug: "tumusime-aniella-vanessa",
    name: "Tumusime Aniella Vanessa",
    institution: "Liquidnet Family High School",
    email: "aniellatumusime01@gmail.com",
    bio: "Aniella's Biography Aniella Vanessa Tumusime is a leader from Rwanda. She believes that the best way to lead is to help people. Aniella Vanessa Tumusime is a student at Liquidnet Family High School at Agahozo-Shalom Youth Village. She works hard to make sure other people have the chance to learn and grow. Aniella Vanessa Tumusime loves working with people and helping them become leaders. She is the Deputy Secretary of the ASYV Model United Nations. Aniella Vanessa Tumusime helps other students get better at speaking and working with people from other countries. Aniella Vanessa Tumusime also works with groups like Girl Up and the Debate Club. She wants to help her friends and make her community a better place. Aniella Vanessa Tumusime believes that young people in Africa can make a difference through the Yale Model African Union V she attended in Ghana Aniella Vanessa Tumusime is good at speaking and has won awards for it. She likes to use her voice to help people talk about issues and work together. Aniella Vanessa Tumusime expresses her feelings, ideas, thoughts through poetry that helps healing others and serving the community though Pay It Forward and Interact with a club that aims to help people around the school community. Aniella Vanessa Tumusime thinks that being a leader is not about having a title. It is about caring about people and helping them when they need it. Aniella Vanessa Tumusime wants to make every place she goes a little better than it was before.",
  },
  {
    slug: "uwase-diane",
    name: "Uwase Diane",
    institution: "Ralga",
    email: "dianeuwase343@gmail.com",
    bio: "My name is UWASE Diane, a graduate in Monetary Economics from the University of Rwanda. I am passionate about leadership, youth empowerment, community development, and creating positive social impact. Through my internship in the Planning Unit at Rulindo District, I gained experience in planning, reporting, data management, and teamwork. I enjoy learning, volunteering, and working with diverse teams to solve challenges. As an ambassador, I am committed to representing the organization with professionalism, integrity, and enthusiasm while inspiring others and contributing to meaningful initiatives.",
  },
  {
    slug: "wendyam-imelda-ozielle-ilboudo",
    name: "Wendyam Imelda Ozielle Ilboudo",
    institution: "Hong Kong Polytechnic University",
    email: "ilboudoimelda8@gmail.com",
    bio: "I am Imelda, a Burkinabè student currently based in Hong Kong, passionate about crochet, faith, and creating opportunities for African youth. I am the founder of Worldwide Crochet and co-founder of Heritage Haven. Participating in YMAU strengthened my leadership and service-oriented skills, and I hope to help others experience the same growth. Outside of my work, I love basketball, dancing, and the quickest way to my heart is ice cream. 🍦",
  },
  {
    slug: "yalled-irakoze",
    name: "Yalled Irakoze",
    institution: "University of Lake Tanganyika/ Tujenge Africa Foundation",
    email: "yirakoze@studentsforliberty.org",
    bio: "Yalled Irakoze is a Computer Science student at the University of Lake Tanganyika and a dedicated Local Coordinator for Students For Liberty. Passionate about youth leadership, technology, and community development, he has extensive experience organizing grassroots educational programs and advocacy events. Yalled is deeply committed to empowering the next generation of African leaders through impactful community engagement, open-source tech initiatives, and collaborative diplomacy.",
  },
  {
    slug: "yannick-mbietow-nouchamboh",
    name: "Yannick Mbietow Nouchamboh",
    institution: "University of Buea, Cameroon",
    email: "nouchambohyannick@gmail.com",
    bio: "Yannick Nouchamboh is a fifth-year medical student at the Faculty of Health Sciences, University of Buea, Cameroon, and a POHER 2026 Scholar. Passionate about neurosurgery, research, and global health, he actively contributes to student leadership through the Cameroon Medical Students' Association (CAMSA) and volunteers with organizations such as Open Dreams to give back to his community. His interests span clinical research, global health, and health systems strengthening, with a particular focus on improving healthcare in Africa. Yannick aspires to become a physician who will drive meaningful and lasting impact beyond the walls of the hospital.",
  },
  {
    slug: "yaw-arko-kyei",
    name: "Yaw Arko Kyei",
    institution: "Ghana Christian International High School",
    email: "yawk2009@gmail.com",
    bio: "I'm Yaw Kyei, a 17 year old Ghanaian boy who just completed high school. I have a lot of hobbies and participate in a lot of extracurricular activities, a few of which are reading, writing spoken word, volleyball, live sound production for events and most important for this case, Model United Nations. I hope to major in mechanical engineering in university, and go on to pursue a full time career in that field.",
  },
  {
    slug: "yvonne-appeynarh",
    name: "Yvonne Appeynarh",
    institution: "Absa Bank Ghana",
    email: "appeynarhyvonne@gmail.com",
    bio: "Yvonne Appeynarh is a Sociology graduate from Ghana with a passion for international development, diplomacy, and social impact. I enjoy writing, creating digital content, and connecting people with life-changing opportunities in education, careers, and leadership. My long-term goal is to build a career in international relations and diplomacy, contributing to policies and initiatives that promote sustainable development, peace, and global cooperation. I believe in continuous learning, meaningful service, and using my skills to create opportunities that empower others.",
  },
];
