import type { MediaAsset } from "./media-library";
import type { CulturalTermKey } from "./cultural-lexicon";

export type PageHeroImage = MediaAsset & {
  nativeLabel?: {
    term: CulturalTermKey;
  };
};

const ymauArchiveCredit = "Official YMAU V media archive";

export const pageHeroImages: Record<string, PageHeroImage> = {
  about: {
    src: "/ymau-media/pages/about.webp",
    alt: "YMAU V delegates gathered for a full conference portrait in Accra",
    context: "The YMAU V delegation · Accra, Ghana",
    credit: ymauArchiveCredit,
    position: "50% 38%",
  },
  history: {
    src: "/ymau-media/pages/history.webp",
    alt: "Delegates gathered in the aisle at the close of YMAU V",
    context: "The conference record · Accra, Ghana",
    credit: ymauArchiveCredit,
    position: "50% 46%",
  },
  founders: {
    src: "/ymau-media/pages/founders.jpg",
    alt: "A portrait triptych of YMAU co-founders Ornella Bayigamba and Richard Mbouombouo with inaugural president Francesca Nyakora",
    context: "YMAU’s founding leadership · 2020–22",
    credit: "Official YMAU institutional archive",
    position: "50% 48%",
  },
  "secretary-general": {
    src: "/ymau-media/pages/secretary-general.webp",
    alt: "A facilitator leading a YMAU V leadership session",
    context: "Leadership in practice · YMAU V",
    credit: ymauArchiveCredit,
    position: "72% 42%",
  },
  secretariat: {
    src: "/ymau-media/pages/secretariat.webp",
    alt: "A YMAU V facilitator leading a room of delegates",
    context: "Leadership training · YMAU V",
    credit: ymauArchiveCredit,
    position: "50% 42%",
  },
  ambassadors: {
    src: "/ymau-media/pages/ambassadors.webp",
    alt: "YMAU V student leaders gathered on stage in Accra",
    context: "A student network in the room · YMAU V",
    credit: ymauArchiveCredit,
    position: "50% 44%",
    nativeLabel: { term: "andinet" },
  },
  careers: {
    src: "/ymau-media/pages/careers-yale-campus.jpg",
    alt: "Students crossing Yale University's Cross Campus toward Sterling Memorial Library",
    context: "Cross Campus · Yale University",
    credit: "Carol M. Highsmith / Library of Congress · Public domain",
    creditHref: "https://commons.wikimedia.org/wiki/File:Cross_Campus_Highsmith.jpg",
    position: "50% 48%",
  },
  programme: {
    src: "/ymau-media/pages/programme.webp",
    alt: "A committee chair addressing delegates during YMAU V",
    context: "Committee session · YMAU V",
    credit: ymauArchiveCredit,
    position: "50% 48%",
  },
  theme: {
    src: "/ymau-media/pages/theme.webp",
    alt: "Stone windows carved into Biete Amanuel in Lalibela, Ethiopia",
    context: "Biete Amanuel · Lalibela, Ethiopia",
    credit: "Francesco Bandarin / UNESCO · CC BY-SA 3.0 IGO",
    creditHref: "https://commons.wikimedia.org/wiki/File:Rock-Hewn_Churches,_Lalibela-107575.jpg",
    position: "50% 52%",
    nativeLabel: { term: "lalibela" },
  },
  "mandate-to-market": {
    src: "/ymau-media/pages/mandate-to-market.webp",
    alt: "A participant pitching an idea on the YMAU V stage",
    context: "Pitch contest · YMAU V",
    credit: ymauArchiveCredit,
    position: "54% 42%",
  },
  "pre-conference": {
    src: "/ymau-media/pages/pre-conference.webp",
    alt: "Delegates raising their hands during YMAU V leadership training",
    context: "Leadership training · YMAU V",
    credit: ymauArchiveCredit,
    position: "60% 40%",
  },
  recap: {
    src: "/ymau-media/editorial/recap-community-wide.jpg",
    alt: "YMAU V delegates, organizers and guests gathered after the closing assembly in Accra",
    context: "Closing assembly · Accra, Ghana",
    credit: ymauArchiveCredit,
    position: "50% 40%",
  },
  committees: {
    src: "/ymau-media/pages/committees.webp",
    alt: "Delegates seated around a committee room during YMAU V",
    context: "Committee session · YMAU V",
    credit: ymauArchiveCredit,
    position: "50% 50%",
  },
  "committee-preparation": {
    src: "/ymau-media/pages/committee-preparation.webp",
    alt: "Delegates exchanging ideas across a YMAU V committee table",
    context: "Delegate exchange · YMAU V",
    credit: ymauArchiveCredit,
    position: "44% 44%",
  },
  "topic-guides": {
    src: "/ymau-media/pages/topic-guides.webp",
    alt: "Country placards and research notes on a YMAU V committee table",
    context: "At the committee table · YMAU V",
    credit: ymauArchiveCredit,
    position: "50% 50%",
  },
  "committee-policies": {
    src: "/ymau-media/pages/committee-policies.webp",
    alt: "Delegates in a focused discussion during YMAU V",
    context: "Structured debate · YMAU V",
    credit: ymauArchiveCredit,
    position: "52% 45%",
  },
  registration: {
    src: "/ymau-media/pages/registration.webp",
    alt: "A student walking through a colourful street in Addis Ababa",
    context: "Everyday Addis Ababa · Ethiopia",
    credit: "Tsion Molla / Pexels",
    creditHref: "https://www.pexels.com/photo/urban-life-in-addis-ababa-with-colorful-scene-36650842/",
    position: "50% 50%",
    nativeLabel: { term: "addisAbaba" },
  },
  "financial-aid": {
    src: "/ymau-media/editorial/financial-aid-recipient-community.jpg",
    alt: "YMAU V delegates and conference leaders celebrating student achievement together",
    context: "Access, achievement and community · YMAU V",
    credit: ymauArchiveCredit,
    position: "50% 46%",
  },
  faq: {
    src: "/ymau-media/pages/faq.webp",
    alt: "The Addis Ababa skyline illuminated at night",
    context: "Addis Ababa after dark · Ethiopia",
    credit: "Abenezer Shewaga / Unsplash",
    creditHref: "https://unsplash.com/photos/WMB-Fb5LHeg",
    position: "50% 48%",
    nativeLabel: { term: "addisAbaba" },
  },
  "travel-guide": {
    src: "/ymau-media/pages/travel-guide.webp",
    alt: "Green highlands near Lalibela and Abune Yosef in Ethiopia",
    context: "Highlands near Lalibela · Ethiopia",
    credit: "Erik Hathaway / Unsplash",
    creditHref: "https://unsplash.com/photos/eRFC0_U0hGE",
    position: "50% 48%",
    nativeLabel: { term: "ethiopia" },
  },
  "addis-ababa": {
    src: "/ymau-media/pages/addis-ababa.webp",
    alt: "Construction cranes and the Addis Ababa skyline at sunset",
    context: "Addis Ababa at dusk · Ethiopia",
    credit: "Jean Rebiffé · CC BY 2.0",
    creditHref: "https://commons.wikimedia.org/wiki/File:Sunset_on_the_rising_city,_Addis_Ababa_-_Flickr_-_jeanotr.jpg",
    position: "50% 48%",
    nativeLabel: { term: "addisAbaba" },
  },
  "city-guide": {
    src: "/ymau-media/pages/city-guide.webp",
    alt: "Coffee being poured from a traditional Ethiopian jebena into small cups",
    context: "Coffee ceremony · Ethiopia",
    credit: "Zeynep S. / Unsplash",
    creditHref: "https://unsplash.com/photos/WcWvmyG73yU",
    position: "50% 46%",
    nativeLabel: { term: "buna" },
  },
  partners: {
    src: "/ymau-media/pages/partners.webp",
    alt: "The African Union headquarters complex in Addis Ababa",
    context: "African Union headquarters · Addis Ababa",
    credit: "Wang Guansen / Xinhua",
    creditHref: "https://commons.wikimedia.org/wiki/File:African_Union_Headquarters_Addis_Ababa.jpg",
    position: "50% 54%",
    nativeLabel: { term: "andinet" },
  },
  "past-partners": {
    src: "/ymau-media/pages/past-partners.webp",
    alt: "A partner recognition plaque presented at YMAU V",
    context: "Partner recognition · YMAU V",
    credit: ymauArchiveCredit,
    position: "50% 52%",
  },
  sponsor: {
    src: "/ymau-media/pages/sponsor.webp",
    alt: "A delegate receiving recognition at the YMAU V awards ceremony",
    context: "Awards ceremony · YMAU V",
    credit: ymauArchiveCredit,
    position: "50% 44%",
  },
  contact: {
    src: "/ymau-media/pages/contact.webp",
    alt: "Delegates in an animated committee discussion during YMAU V",
    context: "Committee exchange · YMAU V",
    credit: ymauArchiveCredit,
    position: "50% 46%",
  },
};
